### ISSUE TITLE
mkversion.sh refers to 'dmd1'

### ISSUE THREAD

**Issue by Geod24** [sociomantic-tsunami/makd#23] opened 2016-10-10 01:12 UTC
```
/mnt/shared/projects/audio/wavegen/submodules/makd/mkversion.sh: line 12: dmd1: command not found
make: Nothing to be done for 'all'.
```

Which comes from here:
https://github.com/sociomantic-tsunami/makd/blob/497a15fe5d6fe8a5079054b21df6295ab5fd1b22/mkversion.sh#L12

I thought [DC should be exported by Makd](https://github.com/sociomantic-tsunami/makd/blob/497a15fe5d6fe8a5079054b21df6295ab5fd1b22/Makd.mak#L103-L109), but apparently it isn't.

Also, there is a small typo in the usage:

> this script doesn't **get** care of quoting, so if you use any 'special'

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-10 08:23
I can't reproduce, have you run it with `DVER=2`. Running `env` from `mkversion.sh` confirms that right `DC` variable is exported.

```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/ocean  git:(v2.x.x) $ make | grep DC
DC=dmd1
^C
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/ocean  git:(v2.x.x) $ make DVER=2 | grep DC
DC=dmd
^C
```

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-10 08:45
OK, I could reproduce. The problem is in the first call of `mkversion`, run through `make`'s `shell` function which does not inherit exported variables:

https://github.com/sociomantic-tsunami/makd/blob/497a15fe5d6fe8a5079054b21df6295ab5fd1b22/Makd.mak#L221

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-10 08:52
Addressed in #24

**Comment by leandro-lucarella-sociomantic** [comment] 2016-10-11 13:30
I wonder why GH is suddenly not closing issues anymore when a commit saying "Fixes #23" is merged.

**Closed as completed by leandro-lucarella-sociomantic** 2016-10-11 13:30 UTC
Labels: type-bug

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-11 13:31
Because that PR was not merged against default branch I think.

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-11 13:32
I wonder if GH would close this issue once v1.5.2 is merged to v1.x.x .

**Comment by nemanja-boric-sociomantic** [comment] 2016-10-11 13:33
https://help.github.com/articles/closing-issues-via-commit-messages/

> If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.
